WIP: feat: convert to typescript
dequelabs/cauldron-react pull request #257
Opened 2020-01-24 20:42 UTC by scurker

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**
- [ ] Follows the commit message policy, appropriate for next version
- [ ] Tested for accessibility
- [ ] Code is reviewed for security

2020-01-24 21:57 UTC, stephenmathieson commented
This is amazing and receives 1,000 gold stars.

2020-02-17 16:07 UTC, schne324 submitted a review, later dismissed
The following demos are broken because of a missing `displayName`:
- https://deploy-preview-257--cauldron-react.netlify.com/components/Button
- https://deploy-preview-257--cauldron-react.netlify.com/components/Checkbox
- https://deploy-preview-257--cauldron-react.netlify.com/components/Link
- https://deploy-preview-257--cauldron-react.netlify.com/components/Toast

2020-02-17 16:13 UTC, stephenmathieson requested changes
Small stuff, plus:

- we shouldn't use global types
- we should keep `MyComponent.propTypes` for non-TS users
- we should keep `MyComponent.displayName` for debugging/demo

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +export interface AlertProps {
Why is this exported?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +  contentRef: RefCallback<HTMLDivElement>;
Where does `RefCallback` come from?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +  static defaultProps = {
IMO we should also have `propTypes` defined for non-TS users. Thoughts?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +  state: AlertState;
```suggestion
readonly state: AlertState;
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +        isolator: new AriaIsolate(this.element as HTMLElement)
What if `this.element` is `null`?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Alert/index.tsx
> +    this.state.isolator?.deactivate();
If `isolator` is `undefined`, should we still `setState` and `onClose`?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Button/index.tsx
> +  buttonRef?: Ref<HTMLButtonElement>;
Where is `Ref` coming from?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Button/index.tsx
> -Button.displayName = 'Button';
Why remove `displayName`?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Button/index.tsx
> +export interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement> {
Why is this exported?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Card/Card.tsx
> +export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {}
```suggestion
type CardProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Card/CardContent.tsx
> +export interface CardContentProps
```suggestion
type CardContentProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Card/CardFooter.tsx
> +export interface CardFooterProps extends React.HTMLAttributes<HTMLDivElement> {}
```suggestion
type CardFooterProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Card/CardHeader.tsx
> +export interface CardHeaderProps extends React.HTMLAttributes<HTMLDivElement> {}
```suggestion
type CardHeaderProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Checkbox/index.tsx
> +import * as React from 'react';
For consistency, do:

```suggestion
import React from 'react';
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Checkbox/index.tsx
> +export interface CheckboxProps
```suggestion
interface CheckboxProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ClickOutsideListener/index.tsx
> +export interface ClickOutsideListenerProps {
```suggestion
interface ClickOutsideListenerProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ClickOutsideListener/index.tsx
> +  handleEvent = (event: MouseEvent | TouchEvent) => {
```suggestion
  handleEvent = (event: MouseEvent<HTMLElement> | TouchEvent<HTMLElement>) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ClickOutsideListener/index.tsx
> +    const target = event.target as HTMLElement;
```suggestion
    const target = event.target
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ClickOutsideListener/index.tsx
> +    let { ref } = this.props.children as any;
Why are you using `any` here?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ClickOutsideListener/index.tsx
> +    return React.cloneElement(props.children as React.ReactElement<any>, {
Why use `any`?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
> +export interface ExpandCollapsePanelProps
```suggestion
interface ExpandCollapsePanelProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
> +  state: ExpandCollapsePanelState = {
```suggestion
  readonly state: ExpandCollapsePanelState = {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
> +  handleToggle = (e: React.MouseEvent<HTMLButtonElement>) => {
```suggestion
  private handleToggle = (e: React.MouseEvent<HTMLButtonElement>) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ExpandCollapsePanel/ExpandCollapsePanel.tsx
> +  panel = React.createRef<HTMLDivElement>();
```suggestion
  private panel = React.createRef<HTMLDivElement>();
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/ExpandCollapsePanel/PanelTrigger.tsx
> +export interface PanelTriggerProps
```suggestion
interface PanelTriggerProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +export interface FirstTimePointOutProps {
```suggestion
interface FirstTimePointOutProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +  getFocusableElements(root: HTMLElement | null) {
```suggestion
  private getFocusableElements(root: HTMLElement | null) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +  handleOffscreenContentFocusIn = ({ target }: FocusEvent) => {
```suggestion
  private handleOffscreenContentFocusIn = ({ target }: FocusEvent) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +  handleOffscreenContentFocusOut = ({ target }: FocusEvent) => {
```suggestion
  private handleOffscreenContentFocusOut = ({ target }: FocusEvent) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +  handleOffscreenFocusIn = ({ target }: FocusEvent) => {
```suggestion
  private handleOffscreenFocusIn = ({ target }: FocusEvent) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/FirstTimePointOut/index.tsx
> +  handleOffscreenFocusOut = ({ target }: FocusEvent) => {
```suggestion
  private handleOffscreenFocusOut = ({ target }: FocusEvent) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Icon/index.tsx
> +export interface IconProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface IconProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Layout/index.tsx
> +export interface LayoutProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
type LayoutProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Link/index.tsx
> +export interface LinkProps
```suggestion
interface LinkProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Loader/index.tsx
> +export interface LoaderProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface LoaderProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Main/index.tsx
> +export interface MainProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface MainProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/MenuItem/index.tsx
> +  onClick(e: React.MouseEvent<HTMLLIElement>) {
```suggestion
  private onClick(e: React.MouseEvent<HTMLLIElement>) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/MenuItem/index.tsx
> +      clickLink(e.target as HTMLElement, this.item as HTMLElement);
Why are these casts needed?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/MenuItem/index.tsx
> +  onKeyDown(e: React.KeyboardEvent<HTMLLIElement>) {
```suggestion
  private onKeyDown(e: React.KeyboardEvent<HTMLLIElement>) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Modal/index.tsx
> +export interface ModalProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface ModalProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Offscreen/index.tsx
> +export interface OffscreenProps extends React.HTMLAttributes<HTMLDivElement> {}
```suggestion
type OffscreenProps = React.HTMLAttributes<HTMLDivElement>
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +export interface OptionsMenuAlignmentProps {
```suggestion
interface OptionsMenuAlignmentProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +export interface OptionsMenuRenderTriggerProps {
```suggestion
interface OptionsMenuRenderTriggerProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +export interface OptionsMenuProps extends OptionsMenuAlignmentProps {
```suggestion
interface OptionsMenuProps extends OptionsMenuAlignmentProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +  toggleMenu = (event: Event) => {
```suggestion
  private toggleMenu = (event: Event) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +  handleTriggerKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {
```suggestion
  private handleTriggerKeyDown = (event: React.KeyboardEvent<HTMLElement>) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenu.tsx
> +      (target as HTMLElement).click();
Why cast?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuItem.tsx
> +export interface OptionsMenuItemProps
```suggestion
interface OptionsMenuItemProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuItem.tsx
> +  handleClick = (event: React.MouseEvent<HTMLElement>) => {
```suggestion
  private handleClick = (event: React.MouseEvent<HTMLElement>) => {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuList.tsx
> +export interface OptionsMenuListProps
```suggestion
interface OptionsMenuListProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuList.tsx
> +    if (menuRef && menuRef.contains(e.target as HTMLElement)) {
Why cast?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuList.tsx
> +    const link = (e.target as HTMLElement).querySelector('a');
Why cast?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuTrigger.tsx
> +export interface OptionsMenuTriggerProps
```suggestion
interface OptionsMenuTriggerProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/OptionsMenu/OptionsMenuWrapper.tsx
> +export interface OptionsMenuWrapperProps
```suggestion
type OptionsMenuWrapperProps = React.HTMLAttributes<HTMLDivElement> & OptionsMenuAlignmentProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/RadioGroup/index.tsx
> +export interface RadioItem extends React.InputHTMLAttributes<HTMLInputElement> {
```suggestion
interface RadioItem extends React.InputHTMLAttributes<HTMLInputElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/RadioGroup/index.tsx
> +export interface RadioGroupProps {
```suggestion
interface RadioGroupProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/RadioGroup/index.tsx
> +  className: string;
Is `className` meant to be required here?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Scrim/index.tsx
> +export interface ScrimProps {
```suggestion
interface ScrimProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Select/index.tsx
> +export interface SelectProps
```suggestion
interface SelectProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Select/index.tsx
> +  findAdjacentEnabledOption(dir: string) {
```suggestion
  private findAdjacentEnabledOption(dir: string) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Select/index.tsx
> +  onTriggerKeydown(e: React.KeyboardEvent<HTMLElement>) {
```suggestion
  private onTriggerKeydown(e: React.KeyboardEvent<HTMLElement>) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Select/index.tsx
> +  onKeyDown(e: React.KeyboardEvent<HTMLElement>) {
```suggestion
  private onKeyDown(e: React.KeyboardEvent<HTMLElement>) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/SideBar/index.tsx
> +export interface SideBarProps extends React.HTMLAttributes<HTMLUListElement> {
```suggestion
interface SideBarProps extends React.HTMLAttributes<HTMLUListElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/SkipLink/index.tsx
> +export interface SkipLinkProps {
```suggestion
interface SkipLinkProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/TextField/index.tsx
> +export interface TextFieldProps
```suggestion
interface TextFieldProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Toast/index.tsx
> +export interface ToastProps {
```suggestion
interface ToastProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Tooltip/index.tsx
> +export interface TooltipProps {
```suggestion
interface TooltipProps {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Tooltip/index.tsx
> +  placement: string;
Should this be a typed string? Does passing "I like dogs" work here?

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/TopBar/TopBar.tsx
> +export interface TopBarProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface TopBarProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/TopBar/TopBar.tsx
> +  onKeyDown(e: React.KeyboardEvent<HTMLElement>) {
```suggestion
  private onKeyDown(e: React.KeyboardEvent<HTMLElement>) {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/TopBar/TopBarMenu.tsx
> +export interface TopBarMenuProps
```suggestion
interface TopBarMenuProps
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/components/Workspace/index.tsx
> +export interface WorkspaceProps extends React.HTMLAttributes<HTMLDivElement> {
```suggestion
interface WorkspaceProps extends React.HTMLAttributes<HTMLDivElement> {
```

2020-02-17 16:13 UTC, stephenmathieson commented on src/global.d.ts
> +type RefCallback<T> = (ref: T | null) => void;
I now see where this stuff is coming from.

Why are these types global? What's wrong with `import`ing them?

2020-02-17 16:14 UTC, stephenmathieson submitted a review, later dismissed
Small stuff, plus:

- we shouldn't use global types
- we should keep `MyComponent.propTypes` for non-TS users
- we should keep `MyComponent.displayName` for debugging/demo

2020-02-17 16:20 UTC, scurker commented on src/components/Card/Card.tsx
> +export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {}
I think we should keep type here to keep component props consistent. If I want to extend a component it feels weird to do `x extends ComponentProp` in some places and `x & ComponentProp` in others

2020-02-17 16:23 UTC, stephenmathieson commented on src/components/Card/Card.tsx
> +export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {}
I disagree. Extending an interface with an empty interface is confusing, whereas aliasing a type to an interface makes sense.

Not going to die on this hill tho. If you have strong feelings here, then leave it as-is.

2020-02-18 16:39 UTC, jeeyyy submitted a review, later dismissed
Did not review all the changes, but the few comments may apply to a large set of files.

2020-02-18 16:39 UTC, jkodu commented on src/components/Alert/index.tsx
> +export const Actions = ({ children }: { children: React.ReactNode }) => (
Seeing that you are de-structuring `children` from rops, I think you could use `PropsWithChildren` interface offered from `react`.

```js
import React, { PropsWithChildren } from 'react'
export const Actions = (props: PropsWithChildren) => <div>{props.children}</div>
```

Will save all the typing necessary for the argument.

2020-02-18 16:39 UTC, jkodu commented on src/components/Alert/index.tsx
> +export interface AlertProps {
```
export interface AlertProps extends PropsWithChildren
```

will save having to define children in the interface

2020-02-18 16:39 UTC, jkodu commented on src/components/Alert/index.tsx
> +  children: React.ReactNode;
nitpick, unsure if this is prettier doing this, but interfaces do not need a semi-colon after each property.

2020-02-18 16:39 UTC, jkodu commented on src/components/Alert/index.tsx
> +  static defaultProps = {
`static defaultProps: AlertProps = {...}`

2020-02-18 16:39 UTC, jkodu commented on src/components/Alert/index.tsx
> +export interface AlertProps {
I think these are exported for when this component is used elsewhere

```
import {Alert, AlertProps} from 'cauldron-react'

const myProps: AlertProps = {...}
<Alert {...myProps} />
```

I may be wrong, I will let @scurker expand on this.

2020-02-18 16:50 UTC, scurker commented on src/components/Alert/index.tsx
> +  children: React.ReactNode;
This is coming from prettier

2020-02-27 21:22 UTC, scurker commented on src/global.d.ts
> +type RefCallback<T> = (ref: T | null) => void;
We should be using the [global type anyway](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L91).

2020-02-28 14:03 UTC, stephenmathieson commented on src/global.d.ts
> +type RefCallback<T> = (ref: T | null) => void;
That's not a _global type_. It's contained by the [`React namespace`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L62-L65). We should not use global types.

Also, I agree that we should be using the types defined by React rather than our own.

2020-02-28 19:45 UTC, scurker commented on src/components/Alert/index.tsx
> +export interface AlertProps {
It looks like it's still expecting a generic type, which doesn't feel right here.

2020-02-28 19:45 UTC, scurker commented on src/components/Alert/index.tsx
> +export interface AlertProps {
Some of these are used in other components, I'd prefer to just export them for consistency.

2020-02-28 20:31 UTC, scurker commented on src/components/Button/index.tsx
> +export interface ButtonProps extends React.HTMLAttributes<HTMLButtonElement> {
For consistency

2020-02-28 20:31 UTC, scurker commented on src/components/Button/index.tsx
> -Button.displayName = 'Button';
It's back

2020-02-28 20:32 UTC, scurker commented on src/components/Card/Card.tsx
> +export interface CardProps extends React.HTMLAttributes<HTMLDivElement> {}
Going to leave this as is due to the size of the pr

2020-02-28 20:38 UTC, scurker commented on src/components/ClickOutsideListener/index.tsx
> +    let { ref } = this.props.children as any;
I couldn't find an accessible `ref` value on any of the exported react types. I would like to avoid this, but I'm not 100% sure we can.

2020-02-28 20:39 UTC, scurker commented on src/components/ClickOutsideListener/index.tsx
> +    return React.cloneElement(props.children as React.ReactElement<any>, {
Because we can't infer the element type here?

2020-02-28 20:43 UTC, scurker commented on src/components/RadioGroup/index.tsx
> +  className: string;
It's a default prop, so it doesn't matter too much either way but I can change that

2020-02-28 20:44 UTC, scurker commented on src/components/Tooltip/index.tsx
> +  placement: string;
Probably, but the placement values come from `rc-tooltip`. I don't really think we should be maintaining those values here as it would be too easy to go out of sync.

2020-02-28 20:45 UTC, scurker commented on src/components/Alert/index.tsx
> +  contentRef: RefCallback<HTMLDivElement>;
It's gone 🚭

2020-02-28 20:46 UTC, scurker commented on src/global.d.ts
> +type RefCallback<T> = (ref: T | null) => void;
I was referring to the react global type, but we're talking about the same thing 🤷‍♂

2020-02-28 20:55 UTC, scurker commented on src/components/Alert/index.tsx
> +export interface AlertProps {
`PropsWithChildren<T>` is unfortunately a generic. I don't think it really makes sense to extend with an empty Prop either `interface AlertProps extends PropsWithChildren<{}>` just feels redundant.

2020-02-28 21:24 UTC, scurker commented on src/components/Alert/index.tsx
> +  static defaultProps = {
Just restored all of the proptypes

2020-02-28 21:32 UTC, scurker commented on src/components/MenuItem/index.tsx
> +      clickLink(e.target as HTMLElement, this.item as HTMLElement);
`clickLink` is expecting `HTMLElement`, but the type returned for target is of type `EventTarget`. Not sure how we work around that.

2020-02-28 21:32 UTC, scurker commented on src/components/OptionsMenu/OptionsMenu.tsx
> +      (target as HTMLElement).click();
The type returned for target is of type `EventTarget`.

2020-02-28 21:33 UTC, scurker commented on src/components/OptionsMenu/OptionsMenuList.tsx
> +    if (menuRef && menuRef.contains(e.target as HTMLElement)) {
The type of target is `EventTarget`.

2020-02-28 21:33 UTC, scurker commented on src/components/OptionsMenu/OptionsMenuList.tsx
> +    const link = (e.target as HTMLElement).querySelector('a');
The type of target is `EventTarget`.

2020-03-01 17:38 UTC, schne324 commented on src/components/Checkbox/index.tsx
>  }
This should fix the [broken demo page](https://deploy-preview-257--cauldron-react.netlify.com/components/Checkbox)
```suggestion
}
Checkbox.displayName = 'Checkbox'
```

2020-03-01 17:40 UTC, schne324 commented on src/components/Toast/index.tsx
>  }
This should fix the [broken Toast demo page](https://deploy-preview-257--cauldron-react.netlify.com/components/Toast)
```suggestion
}

Toast.displayName = 'Toast';
```

2020-03-06 19:19 UTC, scurker commented on src/components/Checkbox/index.tsx
>  }
Added this as a static display value instead

2020-03-06 19:19 UTC, scurker commented on src/components/Toast/index.tsx
>  }
Added this as a static display value instead

2020-03-06 20:13 UTC, scurker commented on src/components/Alert/index.tsx
> +        isolator: new AriaIsolate(this.element as HTMLElement)
`AriaIsolate` does guard against this: 

https://github.com/dequelabs/cauldron-react/blob/07e19622ae30c2f0489cc9c9cd60c6522133861a/src/utils/aria-isolate/index.ts#L9-L13

2020-03-06 20:18 UTC, scurker commented on src/components/Alert/index.tsx
> +    this.state.isolator?.deactivate();
If for some reason `isolator` is `undefined`, I do think we should still attempt to close the dialog. I would consider that a graceful failure.

2020-03-06 20:21 UTC, scurker commented on src/components/ClickOutsideListener/index.tsx
> +    const target = event.target as HTMLElement;
We have to cast it as an `HTMLElement` because `nodeRef.contains(...)` expects and `HTMLElement`.

2020-03-06 20:24 UTC, scurker commented on src/components/MenuItem/index.tsx
> +      clickLink(e.target as HTMLElement, this.item as HTMLElement);
Because `clickLink` expects an `HTMLElement`. And `e.target` is of type `EventTarget`. We have to cast as the expected element because [an `EventTarget` is generic and may not be an HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget).

2020-03-06 22:05 UTC, schne324 approved these changes
everything LGTM. We may want @stephenmathieson to weigh in as he knows more ts than I do

2020-03-10 16:49 UTC, stephenmathieson requested changes
1 thing. Otherwise LGTM!

2020-03-10 16:49 UTC, stephenmathieson commented on package.json
> +  "types": "lib/src/index.d.ts",
This doesn't look right. Why is there a `src` directory in `lib`?

2020-03-10 16:50 UTC, stephenmathieson commented
Pulled this down locally and unfortunately the build process doesn't output TypeScript definitions. We need to fix that before this can land 😭

2020-03-10 16:55 UTC, stephenmathieson commented
It looks like we need to run `tsc --emitDeclarationOnly` to emit type definitions. See https://www.typescriptlang.org/docs/handbook/compiler-options.html

2020-03-10 17:24 UTC, stephenmathieson approved these changes

2020-03-11 16:18 UTC, merged